version: '3.8'

services:
  fitness-webapi:
    build:
      context: .
      dockerfile: FitnessAnalyticsHub.WebApi/Dockerfile
    container_name: fitness-webapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # Strava-Konfiguration aus .env Datei
      - Strava__ClientId=${STRAVA_CLIENT_ID}
      - Strava__ClientSecret=${STRAVA_CLIENT_SECRET}
      - Strava__RedirectUrl=http://localhost:8080/auth/strava/callback
      - Strava__BaseUrl=https://www.strava.com/api/v3/
      - Strava__AuthorizeUrl=https://www.strava.com/oauth/authorize
      - Strava__TokenUrl=https://www.strava.com/oauth/token
      # Datenbank-Verbindung
      - ConnectionStrings__DefaultConnection=Host=database;Database=fitnessanalytics;Username=fitness_user;Password=${DB_PASSWORD}
    volumes:
      - ./data:/app/data
    networks:
      - fitness-network
    restart: unless-stopped

  fitness-ai:
    build:
      context: .
      dockerfile: AIAssistant/Dockerfile
    container_name: fitness-ai
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WebApiBaseUrl=http://fitness-webapi:8080
    depends_on:
      - fitness-webapi
    networks:
      - fitness-network
    restart: unless-stopped

networks:
  fitness-network:
    driver: bridge